name: test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.14t'
        - '3.15t'

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group build --group test
        uv run --no-sync maturin develop --uv
    - name: Test
      run: |
        source .venv/bin/activate
        make test

  linux-purepython:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.14t'
        - '3.15t'

    env:
      UV_PYTHON: ${{ matrix.python-version }}
      # Force to use the purepython modules instead of the native Rust module
      TONIO_USE_NATIVE: 0
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group build --group test
        uv run --no-sync maturin develop --uv
    - name: Test
      run: |
        source .venv/bin/activate
        make test

  macos:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.14t'
        - '3.15t'

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group build --group test
        uv run --no-sync maturin develop --uv --extras=test
    - name: Test
      run: |
        source .venv/bin/activate
        make test

  windows-purepython:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version:
        # Skipping 3.15t on Windows as `cryptography` have not wheel built.
        - '3.14t'

    # The purepython modules are based on asyncio. So Rust modules will not be built.
    # For Windows, just put the source tree on the path.
    defaults:
      run:
        # no changes on Makefile if using bash on Windows
        shell: bash
    env:
      UV_PYTHON: ${{ matrix.python-version }}
      PYTHONPATH: .
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --no-install-project --group test
    - name: Test
      run: |
        uv run --no-sync make test
